apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: django-app-cronjob
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-app-cronjob
            image: your-django-app-cronjob-image:latest
            args:
            - python
            - manage.py
            - your_batch_command
          restartPolicy: OnFailure
