apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: kyverno-test
policies:
  - policies/
resources:
  - manifests/staging/
  - manifests/production/
results:
  - policy: disallow-latest-tag
    rule: require-image-tag
    resource: django-app
    kind: Deployment
    result: pass
  - policy: disallow-latest-tag
    rule: validate-image-tag
    resource: django-app
    kind: Deployment
    result: pass
