name: check

on: pull_request

jobs:
  apply:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - uses: kyverno/action-install-cli@v0.2.0
        with:
          release: 'v1.10.0'

      - run: kyverno version

      - run: kyverno apply policies/ -r manifests/*

  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4

      - uses: kyverno/action-install-cli@v0.2.0
        with:
          release: 'v1.10.0'

      - run: kyverno version

      - run: kyverno test .
